/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.loganh.sandblaster;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_sandblaster=0x7f020000;
        public static final int bigger=0x7f020001;
        public static final int clear=0x7f020002;
        public static final int smaller=0x7f020003;
    }
    public static final class id {
        public static final int palette=0x7f050001;
        public static final int sand=0x7f050000;
    }
    public static final class layout {
        public static final int sand=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int menu_bigger=0x7f040002;
        public static final int menu_clear=0x7f040001;
        public static final int menu_demo=0x7f040004;
        public static final int menu_smaller=0x7f040003;
        public static final int menu_trace_off=0x7f040006;
        public static final int menu_trace_on=0x7f040005;
    }
}
