/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.loganh.sandblaster;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int app_sandblaster=0x7f020000;
        public static final int clear=0x7f020001;
    }
    public static final class id {
        public static final int palette=0x7f050002;
        public static final int picker_layout=0x7f050008;
        public static final int playback=0x7f050003;
        public static final int sand=0x7f050000;
        public static final int save_button=0x7f05000b;
        public static final int save_input=0x7f05000a;
        public static final int save_line=0x7f050009;
        public static final int snapshot_list=0x7f05000c;
        public static final int snapshot_thumbnail=0x7f050006;
        public static final int snapshot_title=0x7f050007;
        public static final int surface=0x7f050001;
        public static final int undo=0x7f050005;
        public static final int zoom=0x7f050004;
    }
    public static final class layout {
        public static final int sand=0x7f030000;
        public static final int snapshot=0x7f030001;
        public static final int snapshot_pick=0x7f030002;
    }
    public static final class string {
        public static final int about_title=0x7f04000a;
        public static final int app_name=0x7f040000;
        public static final int eraser=0x7f040011;
        public static final int load_error_message=0x7f040010;
        public static final int load_error_title=0x7f04000f;
        public static final int menu_about=0x7f040003;
        public static final int menu_clear=0x7f040001;
        public static final int menu_delete_all=0x7f040009;
        public static final int menu_demo=0x7f040002;
        public static final int menu_load=0x7f040005;
        public static final int menu_save=0x7f040004;
        public static final int menu_trace_off=0x7f040008;
        public static final int menu_trace_on=0x7f040007;
        public static final int menu_zoom_to_fit=0x7f040006;
        public static final int save_button=0x7f04000c;
        public static final int save_error_message=0x7f04000e;
        public static final int save_error_title=0x7f04000d;
        public static final int save_hint=0x7f04000b;
    }
}
